/* Compact swipe-to-type dictionary: common English + household / grocery words */
window.SWIPE_WORDS = `
the and for you that with this have from they will what were when your said each about how their she which make like him into time has look two more write see number way could people than first water been call who oil now find long down day did get come made may part over new sound take only little work know place year live back give most very after thing our just name good sentence man think say great where help through much before line right too means old any same tell boy follow came want show also around form three small set put end does another well large must big even such because turn here why ask went men read need land different home move try kind hand picture again change off play spell air away animal house point page letter mother answer found study still learn world high every near add food between own below country plant last school father keep tree never start city earth eye light thought head under story saw left few while along might close something seem next hard open example begin life always those both paper together got group often run important until children side feet car mile night walk white sea began grow took river four carry state once book hear stop without second later miss idea enough eat face watch far real almost let above girl sometimes cut young talk soon list song being leave family body music color stand sun question fish area mark dog horse birds problem complete room knew since ever piece told usually friends easy heard order red door sure become top ship across today during short better best however low hours black products happened whole measure remember early waves reached listen table travel less morning simple several war lay against pattern slow center love person money serve appear road map science rule pull cold notice south voice fall power town fine certain fly unit cry busy itself ocean
please thanks sorry hello yes okay done next later today tomorrow yesterday morning afternoon evening night weekend
milk bread eggs cheese butter yogurt chicken beef pasta rice beans apple apples banana bananas orange oranges grape grapes lemon lime berry strawberry blueberry watermelon peach pear tomato tomatoes potato potatoes onion onions garlic carrot carrots celery lettuce spinach broccoli corn pepper cucumber avocado cereal oatmeal juice soda coffee tea sugar salt ketchup mustard mayo jam honey vinegar flour chips cookies cream pizza burger taco salad soup sandwich toast waffle pancake bacon sausage ham turkey shrimp granola pretzel cracker popcorn candy chocolate cake cookie muffin cupcake pie dessert breakfast lunch dinner snack supper ice
make bed feed walk take out clean wash dry fold put away set clear wipe mop sweep vacuum dust organize pack unpack brush teeth shower bath homework ready shoes door backpack lunchbox permission slip trash recycling compost laundry dishes plants pets tidy table bathroom
reminder dentist soccer practice game party birthday library swim lesson church picnic recital meeting dinner grocery
maya leo zoe sam ava max
`.trim().split(/\s+/);
